Despensa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include #re_path se utiliza para redefinir un path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.Proveedor.urls')),#se dirige al archivo urls.py de tal aplicacion 
    re_path('', include('applications.Cliente.urls')),
    re_path('', include('applications.Producto.urls')),
    re_path('', include('applications.Home.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/Home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'inicio_app'

urlpatterns = [
                path(
                    '',
                    views.Home.as_view(),
                    name='home'
                ),    
                path(
                    'inicio/',
                    views.Home.as_view(),
                    name='inicio'
                ),    
                path(
                    'apiPrueba/',
                    views.Api.as_view(),
                    name='api'
                ),    
]

applications/Producto/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'producto_app'

urlpatterns = [
    path(
        'producto/detalles/<pk>/', #se detalla que registro segun su clave primaria desea detallar
        views.ProductoDetalles.as_view(),
        name='Detalles de producto',
    ),
    path(
        'producto/create/',
        views.ProductoCreateView.as_view(),
        name='Creacion de producto',
    ),  
    path(
        'producto/update/<pk>/', #se detalla que registro segun su clave primaria desea actualizar
        views.ProductoUpdateView.as_view(),
        name='Modificar producto'
    ),
    path(
        'producto/delete/<pk>/',
        views.ProductoDeleteView.as_view(),
        name='Borrar producto'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='login-producto'
    ),
    path(
        'producto/panel/',
        views.Panel.as_view(),
        name='panel-producto'
    ),
    path(
        'producto/logout/',
        views.LogoutView.as_view(),
        name='logout-producto'
    ),
    path(
        'producto/ordenar/identificador',
        views.ProductoIdentificador.as_view(),
        name='producto-identificador'
    ),
    path(
        'producto/ordenar/nombre',
        views.ProductoNombre.as_view(),
        name='producto-nombre'
    ),
    path(
        'producto/ordenar/tipo',
        views.ProductoTipo.as_view(),
        name='producto-tipo'
    ),
    path(
        'producto/ordenar/marcaProd',
        views.ProductoMarca.as_view(),
        name='producto-marca'
    ),
    
    path(
        'producto/api',
        views.ProductoListApiView.as_view(),
        name='api-producto'
    ),
    path(
        'nba/',
        views.GetTeams.as_view(),
        name='nba'
    ),
]

applications/Proveedor/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views 

app_name = 'proveedor_app' 

urlpatterns = [
    path(
        'proveedor/detalles/<pk>/',
        views.ProveedorDetalles.as_view(),
        name='Detalles de proveedor'
    ),
    path(
        'proveedor/create/',
        views.ProveedorCreateView.as_view(),
        name='Creacion de proveedor'
    ),
    path(
        'proveedor/update/<pk>/',
        views.ProveedorUpdateView.as_view(),
        name='Modificar proveedor'
    ),
    path(
        'proveedor/delete/<pk>/',
        views.ProveedorDeleteView.as_view(),
        name='Borrar proveedor'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='login-proveedor'
    ),
    path(
        'proveedor/panel/',
        views.Panel.as_view(),
        name='panel-proveedor'
    ),
    path(
        'proveedor/logout/',
        views.LogoutView.as_view(),
        name='logout-proveedor'
    ),
    path(
        'proveedor/ordenar/identificador',
        views.ProveedorIdentificador.as_view(),
        name='proveedor-identificador'
    ),
    path(
        'proveedor/ordenar/nombre',
        views.ProveedorNombre.as_view(),
        name='proveedor-nombre'
    ),
    path(
        'proveedor/ordenar/rubro',
        views.ProveedorRubro.as_view(),
        name='proveedor-rubro'
    ),
    path(
        'proveedor/api',
        views.ProveedorListApiView.as_view(),
        name='api-proveedor'
    ),
]

applications/Proveedor/models.py
from django.db import models

# Create your models here.
class Proveedor(models.Model):
    """Model definition for Proveedor."""

    identificador = models.IntegerField(primary_key=True)
    nombre = models.CharField("Nombre del proveedor", max_length=50)
    rubro = models.CharField("Rubro del proveedor", max_length=50)


    class Meta:
        """Meta definition for Proveedor."""

        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'

    def __str__(self):
        """Unicode representation of Proveedor."""
        return f"{self.identificador}, {self.nombre}, {self.rubro}"

applications/Proveedor/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from .models import Proveedor
from .form import LoginForm, ProveedorForm
from rest_framework.generics import ListAPIView
from .serializer import ProveedorSerializer
from django.views.generic import (
    View,
    ListView,
    DeleteView,
    CreateView,
    TemplateView,
    UpdateView,
    DetailView
)
from django.views.generic.edit import (
    FormView
)

############################ LOGIN ####################################
class LoginUser(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('proveedor_app:panel-proveedor')
    context_object_name = 'login'
    
    def form_valid(self, form):
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
            )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class Panel(ListView):
    model = Proveedor
    template_name = 'proveedor/panel.html'
    context_object_name = 'proveedor'
    paginate_by = 5

    
    def get_queryset(self):
        #definimos variables donde obtendremos los request
        
        dato = self.request.GET.get('dato','')
        #del model Proveedor filtramos los atributos que necesitamos
        lista = (
            Proveedor.objects.filter(identificador__icontains = dato) 
            | Proveedor.objects.filter(nombre__icontains = dato) 
            | Proveedor.objects.filter(rubro__icontains = dato)
                )
        return lista
    
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'proveedor_app:login-proveedor'
            )
        )

############################ VIEWS ####################################

class ProveedorDetalles(LoginRequiredMixin,DetailView):
    model = Proveedor
    template_name = "proveedor/detalles.html"
    context_object_name = "detalle"
    login_url = reverse_lazy('proveedor_app:login-proveedor')


class ProveedorCreateView(LoginRequiredMixin,CreateView):
    model = Proveedor
    template_name = "proveedor/create.html"
    form_class = ProveedorForm
    login_url = reverse_lazy('proveedor_app:login-proveedor')
    success_url = reverse_lazy('proveedor_app:panel-proveedor') #una vez agregado, vuelve hacia la pag que le pasemos


class ProveedorUpdateView(LoginRequiredMixin,UpdateView):
    model = Proveedor
    template_name = "proveedor/update.html"
    form_class = ProveedorForm
    login_url = reverse_lazy('proveedor_app:login-proveedor')
    success_url = reverse_lazy('proveedor_app:panel-proveedor') #una vez agregado, vuelve hacia la pag que le pasemos


class ProveedorDeleteView(LoginRequiredMixin,DeleteView,DetailView):
    model = Proveedor
    template_name = "proveedor/delete.html"
    context_object_name = 'delete_detail'
    login_url = reverse_lazy('proveedor_app:login-proveedor')
    success_url = reverse_lazy('proveedor_app:panel-proveedor') #una vez agregado, vuelve hacia la pag que le pasemos


############################ VIEWS DE ORDEN ####################################

class ProveedorIdentificador(LoginRequiredMixin,ListView):
    model = Proveedor
    template_name = "proveedor/panel.html"
    ordering = 'identificador'
    paginate_by = 5
    context_object_name = "proveedor"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('proveedor_app:login-proveedor')


class ProveedorNombre(LoginRequiredMixin,ListView):
    model = Proveedor
    template_name = "proveedor/panel.html"
    ordering = 'nombre'
    paginate_by = 5
    context_object_name = "proveedor"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('proveedor_app:login-proveedor')


class ProveedorRubro(LoginRequiredMixin,ListView):
    model = Proveedor
    template_name = "proveedor/panel.html"
    ordering = 'rubro'
    paginate_by = 5
    context_object_name = "proveedor"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('proveedor_app:login-proveedor')
    
############################ API VIEW ####################################
class ProveedorListApiView(ListAPIView):

    serializer_class = ProveedorSerializer

    def get_queryset(self):
        return Proveedor.objects.all()

templates/proveedor/apiView.html
{% extends 'base.html' %}
{% block content %}

<ul>
    {% for proveedor in proveedor %}
            <li>Identificador: {{detalle.identificador}}</li> 
            <li>Nombre: {{detalle.nombre}}</li>
            <li>Rubro: {{detalle.rubro}}</li>
    {% endfor %}
</ul>

{% endblock content %}
    

templates/proveedor/create.html
{% extends 'base.html' %}


{% block content %}
<h1 class="text-center display-4 font-weight-bold font-italic">Alta de Proveedor</h1>

<form method="POST" enctype="multipart/form-data">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
    <div class="alert alert-info">
        <div clas="row m-7 justify-content-center align-items-center">
            <strong>Informacion:</strong> 
            <br>
            Procure completar todos los campos para tener una informacion completa de cada proveedor
        </div>
    </div>
    
    <div class="row mt-5 justify-content-center align-items-center">
        <table>
            {{form.as_table}}
        </table>
    </div>

    <div class="row m-0 justify-content-center mt-4">
        <button class="btn btn-primary text-dark row col-3" type="submit" data-toggle="tooltip" data-placement="right" title="Agregar"><i class="fa-solid fa-user-plus"></i></button>
    </div>

    <div class="row m-0 justify-content-center mt-4">
        <a href="{% url 'proveedor_app:panel-proveedor'%}" class="fa-solid fa-rotate-left btn btn-primary row col-3" data-toggle="tooltip" data-placement="right" title="Volver"></a>
    </div>

</form>

{% endblock content %}

templates/proveedor/delete.html
{% extends 'base.html' %}
{% load static  %}

{% block content %}
    <h1 class="text-center display-4 font-weight-bold font-italic">Borrar Producto</h1>

    <div class="alert alert-warning">
        <div clas="row m-7 justify-content-center align-items-center">
            <strong>¡Advertencia!</strong> 
            <br>
            Usted esta a punto de borrar un proveedor.
        </div>
    </div>

    <h3 class="text-center display-6">¿Desea borrar este proveedor?</h3>

    <div class="row mt-3 justify-content-center">
        <div class="card" style="width: 400px;">
            <img class="card-img-top" src="{% static 'media/Proveedor/user.png' %}" alt="Card image">

            <div class="card-body">            
                <form method="POST">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
                    <p class="card-text">Identificador: {{delete_detail.identificador}}</p> 
                    <p>Nombre: {{delete_detail.nombre}}</p>
                    <p>Tipo: {{delete_detail.rubro}}</p>
                    <button class="btn btn-danger row col-10 ml-4" type="submit" value="Borrar" data-toggle="tooltip" data-placement="right" title="Borrar"><i class="fa-solid fa-user-minus"></i></button>
                    <a href="{% url 'producto_app:panel-producto'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 mt-3" data-toggle="tooltip" data-placement="right" title="Volver"></a>
                </form>
                
            </div>
        </div>
    </div>

{% endblock content %}

templates/proveedor/detalles.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h3 class="text-center display-4 font-weight-bold font-italic">DETALLES DE PROVEEDOR</h3>

<div class="row mt-3 justify-content-center">
    
    <div class="card mt-5" style="width: 400px;">
        {% if detalle.avatar %}
            <img class="card-img-top" src="{{ detalle.avatar.url }}" alt="">
        {% else %}
            <img class="card-img-top" src="{% static 'media/Proveedor/user.png' %}" alt="">
        {% endif %}
            

        <div class="card-body">
            <p class="card-text">Identificador: {{detalle.identificador}}</p> 
            <p class="card-text">Nombre: {{detalle.nombre}}</p>
            <p class="card-text">Rubro: {{detalle.rubro}}</p>
            
            <a href="{% url 'producto_app:panel-producto'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 "></a>
        </div>
    </div>
</div>

{% endblock content %}

templates/proveedor/panel.html
{% extends 'base.html' %}
{% load static %}

{% block panel %}
<h1 class="text-center display-4 font-weight-bold font-italic bg-dark text-light">PANEL DE PROVEEDORES</h1>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center sticky-top">
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    

    <div class="collapse navbar-collapse" id="collapsibleNavbar"> 
        <!-- Links LISTADO PROVEEDORES-->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inicio_app:inicio'%}">INICIO</a>
            </li>
        </ul>
        
        <ul class="navbar-nav mx-auto">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'proveedor_app:Creacion de proveedor'%}">ALTA DE PROVEEDOR</a>
            </li>

            <!-- Dropdown DE ACCIONES -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" data-toggle="tooltip" data-placement="right" title="Refrescar luego de ordenar">
                    ORDENAR
                </a>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'proveedor_app:proveedor-identificador'%}">Por Id</a>
                    <a class="dropdown-item" href="{% url 'proveedor_app:proveedor-nombre'%}">Por Nombre</a>
                    <a class="dropdown-item" href="{% url 'proveedor_app:proveedor-rubro'%}">Por Rubro</a>
                </div>

            </li>

                <a class="navbar-brand" href="{% url 'proveedor_app:panel-proveedor'%}">
                    <i class="fa-solid fa-rotate ml-3" data-toggle="tooltip" data-placement="right" title="Refrescar"></i>
                </a>
<!--                  <p class="navbar-text">Refrescar luego de ordenar</p>     -->
        </ul>

     
        <form method="GET" class="form-inline mx-5 ">
            <input class="form-control" type="text" placeholder="Buscar" id="dato" name="dato">
            <button class="btn btn-lg btn-success fa-solid fa-magnifying-glass" type="submit" data-toggle="tooltip" data-placement="right" title="Buscar"></button>
        </form>        
           <a class="fa-solid fa-circle-xmark btn btn-danger btn-lg" type="submit" href="{% url 'proveedor_app:logout-proveedor'%}"  data-toggle="tooltip" data-placement="right" title="Salir"></a>


    </div>

</nav>



<div class="table-responsive">

    <table class="table table-dark table-hover table-wrapper-scroll-y">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Rubro</th>
                <th>ACCIONES</th>
            </tr>
        </thead>
    

        <tbody>
            
            {% for proveedor in proveedor %}

            <tr>
                <td>{{proveedor.identificador}}</td>
                <td>{{proveedor.nombre}}</td>                 
                <td>{{proveedor.rubro}}</td>
                <td>
                    <div class="dropdown dropright">
                    
                    <button type="button" class="btn btn-outline-warning btn-sm dropdown-toggle" data-toggle="dropdown"> 
                    Accion
                    </button>
                    
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'proveedor_app:Modificar proveedor' proveedor.identificador%}">Modificar</a>
                            <a class="dropdown-item" href="{% url 'proveedor_app:Detalles de proveedor' proveedor.identificador%}">Detalles</a>
                            <a class="dropdown-item" href="{% url 'proveedor_app:Borrar proveedor' proveedor.identificador%}">Borrar</a>
                        </div>
                    </div>
                </td>
            </tr>
            
            {% endfor %}
        
        </tbody>
        
        
  </table>
    
</div>

<ul class="pagination justify-content-center" style="margin:20px 0">
    {% if is_paginated %}
        
        {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a></li>    
        {% endif %}
                
        
        {% for pagina in paginator.page_range %}
            {% ifequal pagina page_obj.number %} 
                <li class="page-item active"><a class="page-link">{{ pagina }}</a></li> 
            
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>       
            {% endifequal %}
        {% endfor %}
            
        {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
        {% endif %}
    {% endif %}
</ul>


{% endblock panel %}

templates/proveedor/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="text-center display-4 font-weight-bold font-italic">Modificacion de Producto</h1>


<div class="alert alert-info">
    <div clas="row m-7 justify-content-center align-items-center">
        <strong>Informacion:</strong> 
        <br>
        Al modificar el DNI de un cliente, debera tener en cuenta que se creara otro cliente con el nuevo DNI modificado. 
        <br>
        Se recomienda eliminar al cliente con DNI obsoleto.
    </div>
</div>
 

<div class="row mt-3 justify-content-center">
    <div class="card" style="width: 500px;">
        
        <img class="card-img-top" src="{% static 'images/prod.png' %}" alt="Card image">

        <div class="card-body">            
            <form method="POST">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
                <table>
                    {{form.as_table}}
                </table>
                <button class="btn btn-warning text-dark row col-10 ml-4 mt-3" type="submit">Modificar</button>

                <a href="{% url 'proveedor_app:panel-proveedor'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 mt-3"></a>
            </form>
        </div>

    </div>
</div>

{% endblock content %}