Despensa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include #re_path se utiliza para redefinir un path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.Proveedor.urls')),#se dirige al archivo urls.py de tal aplicacion 
    re_path('', include('applications.Cliente.urls')),
    re_path('', include('applications.Producto.urls')),
    re_path('', include('applications.Home.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/Cliente/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'cliente_app' 

urlpatterns = [
    path(
        'clientes/detalles/<pk>/', #se detalla que registro segun su clave primaria desea detallar
        views.ClienteDetalles.as_view(),
        name='Detalles de Clientes',
    ),
    path(
        'clientes/create/',
        views.ClienteCreateView.as_view(),
        name='Creacion de Cliente',
    ),
    path(
        'clientes/update/<pk>/', #se detalla que registro segun su clave primaria desea actualizar
        views.ClienteUpdateView.as_view(),
        name='Modificar Cliente'
    ),
    path(
        'clientes/delete/<pk>/',
        views.ClienteDeleteView.as_view(),
        name='Borrar Cliente'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='login-cliente'
    ),
    path(
        'clientes/panel/',
        views.Panel.as_view(),
        name='panel-cliente'
    ),
    path(
        'clientes/logout/',
        views.LogoutView.as_view(),
        name='logout-cliente'
    ),
    path(
        'clientes/ordenar/dni',
        views.ClienteDni.as_view(),
        name='cliente-dni'
    ),
    path(
        'clientes/ordenar/nombre',
        views.ClienteNombre.as_view(),
        name='cliente-nombre'
    ),
    path(
        'clientes/ordenar/apellido',
        views.ClienteApellido.as_view(),
        name='cliente-apellido'
    ),
    
    path(
        'clientes/api',
        views.ClienteListApiView.as_view(),
        name='api-cliente'
    ),
]

applications/Home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'inicio_app'

urlpatterns = [
                path(
                    '',
                    views.Home.as_view(),
                    name='home'
                ),    
                path(
                    'inicio/',
                    views.Home.as_view(),
                    name='inicio'
                ),    
                path(
                    'apiPrueba/',
                    views.Api.as_view(),
                    name='api'
                ),    
]

applications/Cliente/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    """Model definition for Cliente."""

    dni = models.IntegerField(primary_key=True)
    nombre = models.CharField("Nombre", max_length=50)
    apellido = models.CharField("Apellido", max_length=50)
    nombre_completo = models.CharField("Nombre Completo", max_length=50, default='')
    avatar = models.ImageField('avatar', upload_to='Cliente', height_field=None, width_field=None, max_length=None , blank=True)

    class Meta:
        """Meta definition for Cliente."""

        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        """Unicode representation of Cliente."""
        return f"{self.dni}, {self.nombre}, {self.apellido}"

applications/Cliente/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from .models import Cliente
from .form import LoginForm, ClienteForm
from rest_framework.generics import ListAPIView
from .serializer import ClienteSerializer
from django.views.generic import (
    View,
    ListView,
    DeleteView,
    CreateView,
    TemplateView,
    UpdateView,
    DetailView
)
from django.views.generic.edit import (
    FormView
)


############################ LOGIN ####################################
class LoginUser(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('cliente_app:panel-cliente')
    context_object_name = 'login'
    
    def form_valid(self, form):
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
            )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class Panel(ListView):
    model = Cliente
    template_name = 'cliente/panel.html'
    context_object_name = 'clientes'
    paginate_by = 5

    
    def get_queryset(self):
        #definimos variables donde obtendremos los request
        dato = self.request.GET.get('dato','')
        #del model Cliente filtramos los atributos que necesitamos
        lista = Cliente.objects.filter(dni__icontains = dato) | Cliente.objects.filter(nombre__icontains = dato) | Cliente.objects.filter(apellido__icontains = dato)
        return lista
    
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'cliente_app:login-cliente'
            )
        )


############################ VIEWS ####################################
class ClienteDetalles(LoginRequiredMixin,DetailView):  #DETALLES
    model = Cliente
    template_name = "cliente/detalles.html"
    context_object_name = "detalle"
    login_url = reverse_lazy('cliente_app:login-cliente')



class ClienteCreateView(CreateView):    #CREACION
    model = Cliente
    template_name = "cliente/create.html"
    form_class = ClienteForm
    # login_url = reverse_lazy('cliente_app:login-cliente')
    # success_url = reverse_lazy('cliente_app:panel-cliente')
    

    def form_valid(self, form):
        cliente = form.save(commit=False)
        cliente.nombre_completo = f"{cliente.nombre} {cliente.apellido}"
        cliente.save()

        return super(ClienteCreateView, self).form_valid(form)
    
    
class ClienteUpdateView(LoginRequiredMixin,UpdateView):    #ACTUALIZACION
    model = Cliente
    template_name = "cliente/update.html"
    form_class = ClienteForm
    login_url = reverse_lazy('cliente_app:login-cliente')
    success_url = reverse_lazy('cliente_app:panel-cliente')

    def form_valid(self, form):
        cliente = form.save(commit=False)
        cliente.nombre_completo = f"{cliente.nombre} {cliente.apellido}"
        cliente.save()

        return super(ClienteUpdateView, self).form_valid(form)


class ClienteDeleteView(LoginRequiredMixin,DeleteView,DetailView):
    model = Cliente
    template_name = "cliente/delete.html"
    context_object_name = "delete_detail"
    login_url = reverse_lazy('cliente_app:login-cliente')
    success_url = reverse_lazy('cliente_app:panel-cliente')

############################ VIEWS DE ORDEN ####################################

class ClienteDni(LoginRequiredMixin,ListView):
    model = Cliente
    template_name = "cliente/panel.html"
    ordering = 'dni'
    paginate_by = 5
    context_object_name = "clientes"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('cliente_app:login-cliente')


class ClienteNombre(LoginRequiredMixin,ListView):
    model = Cliente
    template_name = "cliente/panel.html"
    ordering = 'nombre'
    paginate_by = 5
    context_object_name = "clientes"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('cliente_app:login-cliente')


class ClienteApellido(LoginRequiredMixin,ListView):
    model = Cliente
    template_name = "cliente/panel.html"
    ordering = 'apellido'
    paginate_by = 5
    context_object_name = "clientes"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('cliente_app:login-cliente')
    

############################ API VIEW ####################################

class ClienteListApiView(ListAPIView):

    serializer_class = ClienteSerializer

    def get_queryset(self):
        return Cliente.objects.all()

templates/cliente/apiView.html
{% extends 'base' %}


{% block content %}

<ul>
    {% for cliente in clientes %}
            <li>{{cliente.nombre}}</li>
            <li>{{cliente.apellido}}</li>
            <li>{{cliente.dni}}</li>
    {% endfor %}
</ul>

{% endblock content %}
    

templates/cliente/create.html
{% extends 'base.html' %}


{% block content %}
<h1 class="text-center display-4 font-weight-bold font-italic">Alta de Clientes</h1>

<form method="POST">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
    <div class="alert alert-info">
        <div clas="row m-7 justify-content-center align-items-center">
            <strong>Informacion:</strong> 
            <br>
            Procure completar todos los campos para tener una informacion completa de cada cliente
        </div>
    </div>
    
    <div class="row mt-5 justify-content-center align-items-center">
        <table>
            {{form.as_table}}
        </table>
    </div>

    <div class="row m-0 justify-content-center mt-4">
        <button class="btn btn-primary text-dark row col-3" type="submit" data-toggle="tooltip" data-placement="right" title="Agregar"><i class="fa-solid fa-user-plus"></i></button>
    </div>

    <div class="row m-0 justify-content-center mt-4">
        <a href="{% url 'cliente_app:panel-cliente'%}" class="fa-solid fa-rotate-left btn btn-primary row col-3" data-toggle="tooltip" data-placement="right" title="Volver"></a>
    </div>

</form>

{% endblock content %}

templates/cliente/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-center display-4 font-weight-bold font-italic">Borrar Clientes</h1>

<div class="alert alert-warning">
    <div clas="row m-7 justify-content-center align-items-center">
        <strong>¡Advertencia!</strong> 
        <br>
        Usted esta a punto de borrar un cliente.
    </div>
</div>

<h3 class="text-center display-6">¿Desea borrar este cliente?</h3>

<div class="row mt-3 justify-content-center">
    <div class="card" style="width: 400px;">
        <img class="card-img-top" src="{% static 'images/user.png' %}" alt="Card image">

        <div class="card-body">            
            <form method="POST">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
                <p>Nombre: {{delete_detail.nombre}}</p>
                <p>Apellido: {{delete_detail.apellido}}</p>
                <p>DNI: {{delete_detail.dni}}</p>
                <button class="btn btn-danger row col-10 ml-4" type="submit" value="Borrar" data-toggle="tooltip" data-placement="right" title="Borrar"><i class="fa-solid fa-user-minus"></i></button>
                <a href="{% url 'cliente_app:panel-cliente'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 mt-3" data-toggle="tooltip" data-placement="right" title="Volver"></a>
            </form>
            
        </div>
    </div>
</div>
{% endblock content %}


     

templates/cliente/detalles.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h3 class="text-center display-4 font-weight-bold font-italic">DETALLES DE CLIENTE</h3>

<div class="row mt-3 justify-content-center">
    
    <div class="card mt-5" style="width: 400px;">
        {% if detalle.avatar %}
            <img class="card-img-top" src="{{ detalle.avatar.url }}" alt="">
        {% else %}
            <img class="card-img-top" src="{% static 'media/Cliente/avatar.png' %}" alt="">
        {% endif %}
            

        <div class="card-body">
            <p class="card-text">Nombre: {{detalle.nombre}}</p> 
            <p class="card-text">Apellido: {{detalle.apellido}}</p>
            <p class="card-text">DNI: {{detalle.dni}}</p>

            <a href="{% url 'cliente_app:panel-cliente' %}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 "></a>
        </div>
    </div>
</div>

{% endblock content %}

templates/cliente/panel.html
{% extends 'base.html' %}
{% load static %}

{% block panel %}
<h1 class="text-center display-4 font-weight-bold font-italic bg-dark text-light">PANEL DE CLIENTES</h1>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center sticky-top">
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar"> 
        <!-- Links LISTADO CLIENTES-->
        
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inicio_app:inicio'%}">INICIO</a>
            </li>
        </ul>
        
        <ul class="navbar-nav mx-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cliente_app:Creacion de Cliente'%}">DAR DE ALTA</a>
            </li>

            <!-- Dropdown DE ACCIONES -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" data-toggle="tooltip" data-placement="right" title="Refrescar luego de ordenar">
                    ORDENAR
                </a>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'cliente_app:cliente-nombre'%}">Por Nombre</a>
                    <a class="dropdown-item" href="{% url 'cliente_app:cliente-apellido'%}">Por Apellido</a>
                    <a class="dropdown-item" href="{% url 'cliente_app:cliente-dni'%}">Por DNI</a>
                </div>

            </li>

                <a class="navbar-brand" href="{% url 'cliente_app:panel-cliente'%}">
                    <i class="fa-solid fa-rotate ml-3" data-toggle="tooltip" data-placement="right" title="Refrescar"></i>
                </a>
<!--                  <p class="navbar-text">Refrescar luego de ordenar</p>     -->
        </ul>

     
        <form method="GET" class="form-inline mx-5 ">
            <input class="form-control" type="text" placeholder="Buscar" id="dato" name="dato">
            <button class="btn btn-lg btn-success fa-solid fa-magnifying-glass" type="submit" data-toggle="tooltip" data-placement="right" title="Buscar"></button>
        </form>        
           <a class="fa-solid fa-circle-xmark btn btn-danger btn-lg" type="submit" href="{% url 'cliente_app:logout-cliente'%}"  data-toggle="tooltip" data-placement="right" title="Salir"></a>


    </div>

</nav>



<div class="table-responsive">

    <table class="table table-dark table-hover table-wrapper-scroll-y">
        <thead>
            <tr>
                <th>DNI</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>ACCIONES</th>
            </tr>
        </thead>
    

        <tbody>
            
            {% for cliente in clientes %}

            <tr>
                <td>{{cliente.dni}}</td>
                <td>{{cliente.nombre}}</td>
                <td>{{cliente.apellido}}</td>
                <td>
                    <div class="dropdown dropright">
                    
                    <button type="button" class="btn btn-outline-warning btn-sm dropdown-toggle" data-toggle="dropdown"> 
                    Accion
                    </button>
                    
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'cliente_app:Modificar Cliente' cliente.dni%}">Modificar</a>
                            <a class="dropdown-item" href="{% url 'cliente_app:Detalles de Clientes' cliente.dni%}">Detalles</a>
                            <a class="dropdown-item" href="{% url 'cliente_app:Borrar Cliente' cliente.dni%}">Borrar</a>
                        </div>
                    </div>
                </td>
            </tr>
        
            {% endfor %}
        
        </tbody>
        
        
  </table>
    
</div>

<ul class="pagination justify-content-center" style="margin:20px 0">
    {% if is_paginated %}
        
        {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a></li>    
        {% endif %}
                
        
        {% for pagina in paginator.page_range %}
            {% ifequal pagina page_obj.number %} 
                <li class="page-item active"><a class="page-link">{{ pagina }}</a></li> 
            
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>       
            {% endifequal %}
        {% endfor %}
            
        {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
        {% endif %}
    {% endif %}
</ul>


{% endblock panel %}

templates/cliente/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-center display-4 font-weight-bold font-italic">Modificacion de Clientes</h1>

<div class="alert alert-info">
    <div clas="row m-7 justify-content-center align-items-center">
        <strong>Informacion:</strong> 
        <br>
        Al modificar el DNI de un cliente, debera tener en cuenta que se creara otro cliente con el nuevo DNI modificado. 
        <br>
        Se recomienda eliminar al cliente con DNI obsoleto.
    </div>
</div>
 

<div class="row mt-3 justify-content-center">
    <div class="card" style="width: 500px;">
        
        <img class="card-img-top" src="{% static 'images/user.png' %}" alt="Card image">

        <div class="card-body">            
            <form method="POST">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
                <table>
                    {{form.as_table}}
                </table>
                <button class="btn btn-warning text-dark row col-10 ml-4 mt-3" type="submit">Modificar</button>

                <a href="{% url 'cliente_app:panel-cliente'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 mt-3"></a>
            </form>
        </div>

    </div>
</div>
{% endblock content %}