Despensa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include #re_path se utiliza para redefinir un path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.Proveedor.urls')),#se dirige al archivo urls.py de tal aplicacion 
    re_path('', include('applications.Cliente.urls')),
    re_path('', include('applications.Producto.urls')),
    re_path('', include('applications.Home.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/Home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'inicio_app'

urlpatterns = [
                path(
                    '',
                    views.Home.as_view(),
                    name='home'
                ),    
                path(
                    'inicio/',
                    views.Home.as_view(),
                    name='inicio'
                ),    
                path(
                    'apiPrueba/',
                    views.Api.as_view(),
                    name='api'
                ),    
]

applications/Producto/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'producto_app'

urlpatterns = [
    path(
        'producto/detalles/<pk>/', #se detalla que registro segun su clave primaria desea detallar
        views.ProductoDetalles.as_view(),
        name='Detalles de producto',
    ),
    path(
        'producto/create/',
        views.ProductoCreateView.as_view(),
        name='Creacion de producto',
    ),  
    path(
        'producto/update/<pk>/', #se detalla que registro segun su clave primaria desea actualizar
        views.ProductoUpdateView.as_view(),
        name='Modificar producto'
    ),
    path(
        'producto/delete/<pk>/',
        views.ProductoDeleteView.as_view(),
        name='Borrar producto'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='login-producto'
    ),
    path(
        'producto/panel/',
        views.Panel.as_view(),
        name='panel-producto'
    ),
    path(
        'producto/logout/',
        views.LogoutView.as_view(),
        name='logout-producto'
    ),
    path(
        'producto/ordenar/identificador',
        views.ProductoIdentificador.as_view(),
        name='producto-identificador'
    ),
    path(
        'producto/ordenar/nombre',
        views.ProductoNombre.as_view(),
        name='producto-nombre'
    ),
    path(
        'producto/ordenar/tipo',
        views.ProductoTipo.as_view(),
        name='producto-tipo'
    ),
    path(
        'producto/ordenar/marcaProd',
        views.ProductoMarca.as_view(),
        name='producto-marca'
    ),
    
    path(
        'producto/api',
        views.ProductoListApiView.as_view(),
        name='api-producto'
    ),
    path(
        'nba/',
        views.GetTeams.as_view(),
        name='nba'
    ),
]

applications/Producto/models.py
from django.db import models
from applications.Proveedor.models import Proveedor

# Create your models here.
class Marca(models.Model):
    """Model definition for Marca."""

    marca = models.CharField("Marca", max_length=50)
    
    class Meta:
        """Meta definition for Marca."""

        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    def __str__(self):
        """Unicode representation of Marca."""
        return self.marca


class Producto(models.Model):
    """Model definition for Producto."""
    identificador = models.IntegerField(primary_key=True)
    nombre = models.CharField('Nombre', max_length=50,default='')
    tipo = models.CharField("Tipo de producto", max_length=50)
    marca = models.ManyToManyField(Marca)
    cantidad = models.IntegerField(default=0)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE,default='')
    
    class Meta:
        """Meta definition for Producto."""

        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        """Unicode representation of Producto."""
        return f"{self.identificador} {self.nombre}"

applications/Producto/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from .models import Producto
from .form import LoginForm, ProductoForm
from django.views.generic.edit import FormView
from rest_framework.generics import ListAPIView
from .serializer import ProductoSerializer
from django.views.generic import (
    View,
    ListView,
    DeleteView,
    CreateView,
    TemplateView,
    UpdateView,
    DetailView
)

from .services import get_nbaTeams

############################ LOGIN ####################################
class LoginUser(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('producto_app:panel-producto')
    context_object_name = 'login'
    
    def form_valid(self, form):
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
            )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class Panel(ListView):
    model = Producto
    template_name = 'producto/panel.html'
    context_object_name = 'productos'
    paginate_by = 5
    
    def get_queryset(self):
        #definimos variables donde obtendremos los request
        dato = self.request.GET.get('dato','')
        #del model Producto filtramos los atributos que necesitamos
        lista = (
            Producto.objects.filter(identificador__icontains = dato) 
            | Producto.objects.filter(nombre__icontains = dato) 
            | Producto.objects.filter(tipo__icontains = dato) 
        )
        return lista
    
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'producto_app:login-producto'
            )
        )

############################ VIEWS ####################################


class ProductoDetalles(LoginRequiredMixin,DetailView):    
    model = Producto
    template_name = "producto/detalles.html"      
    context_object_name = "detalle"
    login_url = reverse_lazy('producto_app:login-producto')


class ProductoCreateView(LoginRequiredMixin,CreateView):    #CREACION LoginRequery
    model = Producto
    template_name = "producto/create.html"
    form_class = ProductoForm
    success_url = reverse_lazy('producto_app:panel-producto') #una vez agregado, vuelve hacia la pag que le pasemos
    login_url = reverse_lazy('producto_app:login-producto')


class ProductoUpdateView(LoginRequiredMixin,UpdateView):  #BUSQUEDA SEGUN CRITERIO
    model = Producto
    template_name = 'producto/update.html'
    form_class = ProductoForm
    context_object_name = 'productos'    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    success_url = reverse_lazy('producto_app:panel-producto')
    login_url = reverse_lazy('producto_app:login-producto')

   

class ProductoDeleteView(LoginRequiredMixin,DeleteView,DetailView):  
    model = Producto
    template_name = "producto/delete.html"
    context_object_name = "delete_detail"
    success_url = reverse_lazy('producto_app:panel-producto')
    login_url = reverse_lazy('producto_app:login-producto')

############################ VIEWS DE ORDEN ####################################

class ProductoIdentificador(LoginRequiredMixin,ListView):
    model = Producto
    template_name = "producto/panel.html"
    ordering = 'identificador'
    paginate_by = 5
    context_object_name = "productos"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('producto_app:login-producto')


class ProductoNombre(LoginRequiredMixin,ListView):
    model = Producto
    template_name = "producto/panel.html"
    ordering = 'nombre'
    paginate_by = 5
    context_object_name = "productos"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('producto_app:login-producto')


class ProductoTipo(LoginRequiredMixin,ListView):
    model = Producto
    template_name = "producto/panel.html"
    ordering = 'tipo'
    paginate_by = 5
    context_object_name = "productos"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('producto_app:login-producto')
    
class ProductoMarca(LoginRequiredMixin,ListView):
    model = Producto
    template_name = "producto/panel.html"
    ordering = 'marca'
    paginate_by = 5
    context_object_name = "productos"    #los objetos que las vistas mandan al template para ver clioentes tienen nombres por defecto, con esto le asignamos un nombre
    login_url = reverse_lazy('producto_app:login-producto')


############################ API VIEW ####################################


class ProductoListApiView(ListAPIView):

    serializer_class = ProductoSerializer

    def get_queryset(self):
        return Producto.objects.all()
    
class GetTeams(TemplateView):
    template_name = 'nbaTeams.html'
    
    def get_context_data(self, **kwargs):
        context = {
            'nbaTeams' : get_nbaTeams()
        }
        return context
    

templates/producto/apiView.html
{% extends 'base' %}


{% block content %}

<ul>
    {% for producto in productos %}
            <li>Identificador: {{detalle.identificador}}</li> 
            <li>Nombre: {{detalle.nombre}}</li>
            <li>Tipo: {{detalle.tipo}}</li>
            <li>Marca de producto: {{detalle.marcaProd}}</li>
    {% endfor %}
</ul>

{% endblock content %}
    

templates/producto/create.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center display-4 font-weight-bold font-italic">Agregar Producto</h1>

<form method="POST" enctype="multipart/form-data">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
    <div class="alert alert-info">
        <div clas="row m-7 justify-content-center align-items-center">
            <strong>Informacion:</strong> 
            <br>
            Procure completar todos los campos para tener una informacion completa de cada producto
        </div>
    </div>
    
    <div class="row mt-5 justify-content-center align-items-center">
        <table>
            {{form.as_table}}
        </table>
    </div>

    <div class="row m-0 justify-content-center mt-4">
        <button class="btn btn-primary text-dark row col-3" type="submit" data-toggle="tooltip" data-placement="right" title="Agregar"><i class="fa-solid fa-user-plus"></i></button>
    </div>

    <div class="row m-0 justify-content-center mt-4">
        <a href="{% url 'producto_app:panel-producto'%}" class="fa-solid fa-rotate-left btn btn-primary row col-3" data-toggle="tooltip" data-placement="right" title="Volver"></a>
    </div>

</form>

{% endblock content %}

templates/producto/delete.html
{% extends 'base.html' %}
{% load static  %}

{% block content %}
    <h1 class="text-center display-4 font-weight-bold font-italic">Borrar Producto</h1>

    <div class="alert alert-warning">
        <div clas="row m-7 justify-content-center align-items-center">
            <strong>¡Advertencia!</strong> 
            <br>
            Usted esta a punto de borrar un producto.
        </div>
    </div>

    <h3 class="text-center display-6">¿Desea borrar este producto?</h3>

    <div class="row mt-3 justify-content-center">
        <div class="card" style="width: 400px;">
            <img class="card-img-top" src="{% static 'images/prod.png' %}" alt="Card image">

            <div class="card-body">            
                <form method="POST">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
                    <p class="card-text">Identificador: {{delete_detail.identificador}}</p> 
                    <p>Nombre: {{delete_detail.nombre}}</p>
                    <p>Tipo: {{delete_detail.tipo}}</p>
                    {% for item in delete_detail.marca.all %}
                    <p> Marca de producto: {{item.marca}}</p>
                    {% endfor %}
                    <button class="btn btn-danger row col-10 ml-4" type="submit" value="Borrar" data-toggle="tooltip" data-placement="right" title="Borrar"><i class="fa-solid fa-user-minus"></i></button>
                    <a href="{% url 'producto_app:panel-producto'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 mt-3" data-toggle="tooltip" data-placement="right" title="Volver"></a>
                </form>
                
            </div>
        </div>
    </div>

{% endblock content %}

templates/producto/detalles.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h3 class="text-center display-4 font-weight-bold font-italic">DETALLES DE PRODUCTO</h3>

<div class="row mt-3 justify-content-center">
    
    <div class="card mt-5" style="width: 400px;">
        {% if detalle.avatar %}
            <img class="card-img-top" src="{{ detalle.avatar.url }}" alt="">
        {% else %}
            <img class="card-img-top" src="{% static 'media/Producto/prod.png' %}" alt="">
        {% endif %}
            

        <div class="card-body">
            <p class="card-text">Identificador: {{detalle.identificador}}</p> 
            <p class="card-text">Nombre: {{detalle.nombre}}</p>
            <p class="card-text">Tipo: {{detalle.tipo}}</p>
            
            {% for item in detalle.marca.all %}
            <p class="card-text"> Marca de producto: {{item.marca}}</p>
            {% endfor %}

            <p class="card-text">Cantidad: {{detalle.cantidad}}</p>
            <p class="card-text">Proveedor: {{detalle.proveedor.nombre}}</p>

            
            <a href="{% url 'producto_app:panel-producto'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 "></a>
        </div>
    </div>
</div>

{% endblock content %}

templates/producto/panel.html
{% extends 'base.html' %}
{% load static %}

{% block panel %}
<h1 class="text-center display-4 font-weight-bold font-italic bg-dark text-light">PANEL DE PRODUCTOS</h1>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center sticky-top">
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar"> 
        <!-- Links LISTADO PRODUCTOS-->

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inicio_app:inicio'%}">INICIO</a>
            </li>
        </ul>
        
        <ul class="navbar-nav mx-auto">
        
            <li class="nav-item">
                <a class="nav-link" href="{% url 'producto_app:Creacion de producto'%}">AGREGAR PRODUCTO</a>
            </li>

            <!-- Dropdown DE ACCIONES -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" data-toggle="tooltip" data-placement="right" title="Refrescar luego de ordenar">
                    ORDENAR
                </a>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'producto_app:producto-nombre'%}">Por Nombre</a>
                    <a class="dropdown-item" href="{% url 'producto_app:producto-marca'%}">Por Marca</a>
                </div>

            </li>

                <a class="navbar-brand" href="{% url 'producto_app:panel-producto'%}">
                    <i class="fa-solid fa-rotate ml-3" data-toggle="tooltip" data-placement="right" title="Refrescar"></i>
                </a>
<!--                  <p class="navbar-text">Refrescar luego de ordenar</p>     -->
        </ul>

     
        <form method="GET" class="form-inline mx-5 ">
            <input class="form-control" type="text" placeholder="Buscar" id="dato" name="dato">
            <button class="btn btn-lg btn-success fa-solid fa-magnifying-glass" type="submit" data-toggle="tooltip" data-placement="right" title="Buscar"></button>
        </form>        
           <a class="fa-solid fa-circle-xmark btn btn-danger btn-lg" type="submit" href="{% url 'producto_app:logout-producto'%}"  data-toggle="tooltip" data-placement="right" title="Salir"></a>


    </div>

</nav>



<div class="table-responsive">

    <table class="table table-dark table-hover table-wrapper-scroll-y">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Marca</th>
                <th>Proveedor</th>
                <th>Cantidad</th>
                <th>ACCIONES</th>
            </tr>
        </thead>
    

        <tbody>
            
            {% for producto in productos  %}

            <tr>
                <td>{{producto.identificador}}</td>
                <td>{{producto.nombre}}</td>

                {% for item in producto.marca.all %}
                    <td>{{item.marca}}</td>
                {% endfor %}
                    
                <td>{{producto.proveedor.nombre}}</td>
                <td>{{producto.cantidad}}</td>
                <td>   
                    <div class="dropdown dropright">
                    
                    <button type="button" class="btn btn-outline-warning btn-sm dropdown-toggle" data-toggle="dropdown"> 
                    Accion
                    </button>
                    
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'producto_app:Modificar producto' producto.identificador%}">Modificar</a>
                            <a class="dropdown-item" href="{% url 'producto_app:Detalles de producto' producto.identificador%}">Detalles</a>
                            <a class="dropdown-item" href="{% url 'producto_app:Borrar producto' producto.identificador%}">Borrar</a>
                        </div>
                    </div>
                </td>
            </tr>
            
            {% endfor %}
        
        </tbody>
        
        
  </table>
    
</div>

<ul class="pagination justify-content-center" style="margin:20px 0">
    {% if is_paginated %}
        
        {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a></li>    
        {% endif %}
                
        
        {% for pagina in paginator.page_range %}
            {% ifequal pagina page_obj.number %} 
                <li class="page-item active"><a class="page-link">{{ pagina }}</a></li> 
            
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>       
            {% endifequal %}
        {% endfor %}
            
        {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
        {% endif %}
    {% endif %}
</ul>


{% endblock panel %}

templates/producto/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="text-center display-4 font-weight-bold font-italic">Modificacion de Producto</h1>


<div class="alert alert-info">
    <div clas="row m-7 justify-content-center align-items-center">
        <strong>Informacion:</strong> 
        <br>
        Al modificar el DNI de un cliente, debera tener en cuenta que se creara otro cliente con el nuevo DNI modificado. 
        <br>
        Se recomienda eliminar al cliente con DNI obsoleto.
    </div>
</div>


<div class="row mt-3 justify-content-center">
    <div class="card" style="width: 500px;">
        
        <img class="card-img-top" src="{% static 'images/prod.png' %}" alt="Card image">

        <div class="card-body">            
            <form method="POST">{% csrf_token %}    <!-- Permite prevenir falsificaciónes de solicitudes entre sitios.-->
                <table>
                    {{form.as_table}}
                </table>
                <button class="btn btn-warning text-dark row col-10 ml-4 mt-3" type="submit">Modificar</button>

                <a href="{% url 'producto_app:panel-producto'%}" class="fa-solid fa-rotate-left btn btn-primary row col-10 ml-4 mt-3"></a>
            </form>
        </div>

    </div>
</div>

{% endblock content %}