Despensa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include #re_path se utiliza para redefinir un path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.Proveedor.urls')),#se dirige al archivo urls.py de tal aplicacion 
    re_path('', include('applications.Cliente.urls')),
    re_path('', include('applications.Producto.urls')),
    re_path('', include('applications.Home.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/Cliente/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'cliente_app' 

urlpatterns = [
    path(
        'clientes/detalles/<pk>/', #se detalla que registro segun su clave primaria desea detallar
        views.ClienteDetalles.as_view(),
        name='Detalles de Clientes',
    ),
    path(
        'clientes/create/',
        views.ClienteCreateView.as_view(),
        name='Creacion de Cliente',
    ),
    path(
        'clientes/update/<pk>/', #se detalla que registro segun su clave primaria desea actualizar
        views.ClienteUpdateView.as_view(),
        name='Modificar Cliente'
    ),
    path(
        'clientes/delete/<pk>/',
        views.ClienteDeleteView.as_view(),
        name='Borrar Cliente'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='login-cliente'
    ),
    path(
        'clientes/panel/',
        views.Panel.as_view(),
        name='panel-cliente'
    ),
    path(
        'clientes/logout/',
        views.LogoutView.as_view(),
        name='logout-cliente'
    ),
    path(
        'clientes/ordenar/dni',
        views.ClienteDni.as_view(),
        name='cliente-dni'
    ),
    path(
        'clientes/ordenar/nombre',
        views.ClienteNombre.as_view(),
        name='cliente-nombre'
    ),
    path(
        'clientes/ordenar/apellido',
        views.ClienteApellido.as_view(),
        name='cliente-apellido'
    ),
    
    path(
        'clientes/api',
        views.ClienteListApiView.as_view(),
        name='api-cliente'
    ),
]

applications/Home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'inicio_app'

urlpatterns = [
                path(
                    '',
                    views.Home.as_view(),
                    name='home'
                ),    
                path(
                    'inicio/',
                    views.Home.as_view(),
                    name='inicio'
                ),    
                path(
                    'apiPrueba/',
                    views.Api.as_view(),
                    name='api'
                ),    
]

applications/Producto/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'producto_app'

urlpatterns = [
    path(
        'producto/detalles/<pk>/', #se detalla que registro segun su clave primaria desea detallar
        views.ProductoDetalles.as_view(),
        name='Detalles de producto',
    ),
    path(
        'producto/create/',
        views.ProductoCreateView.as_view(),
        name='Creacion de producto',
    ),  
    path(
        'producto/update/<pk>/', #se detalla que registro segun su clave primaria desea actualizar
        views.ProductoUpdateView.as_view(),
        name='Modificar producto'
    ),
    path(
        'producto/delete/<pk>/',
        views.ProductoDeleteView.as_view(),
        name='Borrar producto'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='login-producto'
    ),
    path(
        'producto/panel/',
        views.Panel.as_view(),
        name='panel-producto'
    ),
    path(
        'producto/logout/',
        views.LogoutView.as_view(),
        name='logout-producto'
    ),
    path(
        'producto/ordenar/identificador',
        views.ProductoIdentificador.as_view(),
        name='producto-identificador'
    ),
    path(
        'producto/ordenar/nombre',
        views.ProductoNombre.as_view(),
        name='producto-nombre'
    ),
    path(
        'producto/ordenar/tipo',
        views.ProductoTipo.as_view(),
        name='producto-tipo'
    ),
    path(
        'producto/ordenar/marcaProd',
        views.ProductoMarca.as_view(),
        name='producto-marca'
    ),
    
    path(
        'producto/api',
        views.ProductoListApiView.as_view(),
        name='api-producto'
    ),
    path(
        'nba/',
        views.GetTeams.as_view(),
        name='nba'
    ),
]

applications/Proveedor/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views 

app_name = 'proveedor_app' 

urlpatterns = [
    path(
        'proveedor/detalles/<pk>/',
        views.ProveedorDetalles.as_view(),
        name='Detalles de proveedor'
    ),
    path(
        'proveedor/create/',
        views.ProveedorCreateView.as_view(),
        name='Creacion de proveedor'
    ),
    path(
        'proveedor/update/<pk>/',
        views.ProveedorUpdateView.as_view(),
        name='Modificar proveedor'
    ),
    path(
        'proveedor/delete/<pk>/',
        views.ProveedorDeleteView.as_view(),
        name='Borrar proveedor'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='login-proveedor'
    ),
    path(
        'proveedor/panel/',
        views.Panel.as_view(),
        name='panel-proveedor'
    ),
    path(
        'proveedor/logout/',
        views.LogoutView.as_view(),
        name='logout-proveedor'
    ),
    path(
        'proveedor/ordenar/identificador',
        views.ProveedorIdentificador.as_view(),
        name='proveedor-identificador'
    ),
    path(
        'proveedor/ordenar/nombre',
        views.ProveedorNombre.as_view(),
        name='proveedor-nombre'
    ),
    path(
        'proveedor/ordenar/rubro',
        views.ProveedorRubro.as_view(),
        name='proveedor-rubro'
    ),
    path(
        'proveedor/api',
        views.ProveedorListApiView.as_view(),
        name='api-proveedor'
    ),
]

applications/Home/models.py
from django.db import models

# Create your models here.

applications/Home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .services import anime

############################ HOME VIEW ####################################

class Home(TemplateView):
    template_name = 'home.html'
    
class Api(TemplateView):
    template_name = 'api.html'
    context_object_name = 'api_data'
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    
    <title>Despensa con Django</title>

</head>
<body>
    <div>
        {% block home %}
        {% endblock home %}

        {% block panel %}
        {% endblock panel %}
        
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block home %}
<style>
    .carousel-inner img {
        width: 80%;
        height: 100%;
      }
</style>
    
<nav class="navbar navbar-expand-sm bg-dark p-2 navbar-dark p-2 justify-content-center sticky-top">
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="collapsibleNavbar"> 
        <a class="navbar-brand" href="#">
            <i class="fa-solid fa-shop"></i>
        </a>
    </div>
    
    <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar"> 
        <!-- Links LISTADO PROVEEDORES-->
        <ul class="navbar-nav">             
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cliente_app:panel-cliente'%}">CLIENTES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'producto_app:panel-producto'%}">PRODUCTOS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'proveedor_app:panel-proveedor'%}">PROVEEDORES</a>
            </li>
        </ul>
    </div>
    
    <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar"> 
        <ul class="navbar-nav">
            <li class="nav-item dropdown dropleft">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  API REST
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'cliente_app:api-cliente'%}" target="_blank">Cliente</a>
                    <a class="dropdown-item" href="{% url 'producto_app:api-producto'%}" target="_blank" >Producto</a>
                    <a class="dropdown-item" href="{% url 'proveedor_app:api-proveedor'%}" target="_blank" >Proveedor</a>
                </div>
              </li>
        </ul>
    </div>

</nav>
    <!--CARRUSEL-->
    <div id="demo" class="carousel slide" data-ride="carousel">

        <!-- INDICADORES CARRUSEL -->
        <ul class="carousel-indicators">
          <li data-target="#demo" data-slide-to="0"></li>
          <li data-target="#demo" data-slide-to="1"></li>
          <li data-target="#demo" data-slide-to="2"></li>
          <li data-target="#demo" data-slide-to="3"></li>
        </ul>
      
        <!-- DIAPOSITIVAS -->
        <div class="carousel-inner">

            <div class="carousel-item active">
                <img class="img-fluid mx-auto d-block" src="{% static 'media/c1.webp'%}" alt="bienvenido">
                <div class="carousel-caption">
                    <h3 class="display-4 bg-dark font-italic "><i class="fa-solid fa-house"></i> BIENVENIDO <i class="fa-solid fa-house"></i></h3>
                    <p class="bg-dark p-2">Este sistema de gestion le permitira realizar funciones de alta, baja, modificacion y creacion de registros</p>
                </div>
            </div>
            
            <div class="carousel-item">
                <img class="img-fluid mx-auto d-block"  src="{% static 'media/Cliente/c2.png'%}" alt="clientes">
                <div class="carousel-caption">
                    <h3 class="display-4 bg-dark font-italic"><i class="fa-solid fa-users"></i> CLIENTES <i class="fa-solid fa-users"></i></h3>
                    <p class="bg-dark p-2">Registre sus clientes mas habituales</p>
                </div>
            </div>
            
            <div class="carousel-item">
                <img class="img-fluid mx-auto d-block" src="{% static 'media/Producto/c3.webp'%}" alt="productos" style="width: 75%;">
                <div class="carousel-caption">
                    <h3 class="display-4 bg-dark font-italic"><i class="fa-solid fa-boxes-packing"></i> PRODUCTOS <i class="fa-solid fa-boxes-packing"></i></h3>
                    <p class="bg-dark p-2">Lleve un control completo y detallado de sus productos</p>
                </div>
            </div>

            <div class="carousel-item">
              <img class="img-fluid mx-auto d-block" src="{% static 'media/Proveedor/c4.webp'%}" alt="proveedores" style="width: 65%;">
              <div class="carousel-caption">
                    <h3 class="display-4 bg-dark p-2 font-italic"><i class="fa-solid fa-truck-field"></i> PROVEEDORES <i class="fa-solid fa-truck-field"></i></h3>
                    <p class="bg-dark p-2">Gestione los proveedores que necesita su negocio</p>
                </div>
            </div>
        </div>
    </div>
    
    <!--CONTROLES DE DIAPOSITIVAS (DERECHA O IZQUIERDA) -->
    <div>
        <!-- IZQUIERDA-->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon bg-dark"></span>
        </a>

        <!-- DERECHA -->
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon bg-dark"></span>
        </a>
      
    </div>

{% endblock home %}
    

templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <h1 class="text-center display-4 font-weight-bold font-italic">Acceso al Sistema</h1>


    <form method="POST">{% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-primary fa-solid fa-right-to-bracket btn-lg" data-toggle="tooltip" data-placement="right" title="Ingresar"></button>
    </form>
</div>

{% endblock content %}
    

templates/nbaTeams.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>NBA TEAMS</title>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    
    </head>

    <body>
        <div class='container-sm'>    
            
                <table class="table table-dark table-hover">
                    <thead class="sticky-top bg-dark">
                        <tr>
                            <th>ID</th>
                            <th>Abreviacion</th>
                            <th>Ciudad</th>
                            <th>Conferencia</th>
                            <th>Division</th>
                            <th>Nombre Completo</th>
                            <th>Nombre</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for team in nbaTeams %}
                        
                            <tr>
                                <td>{{team.id}}</td>
                                <td>{{team.abbreviation}}</td>
                                <td>{{team.city}}</td>
                                <td>{{team.conference}}</td>
                                <td>{{team.division}}</td>
                                <td>{{team.full_name}}</td>
                                <td>{{team.name}}</td>
                            </tr>
                        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        
    </body>
</html>